"""empty message

Revision ID: 4034e964b93b
Revises: 3a591c51cc96
Create Date: 2022-02-26 14:11:35.499726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4034e964b93b'
down_revision = '3a591c51cc96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'passwordcifrada')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('passwordcifrada', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
